# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Xilinx/Project/pipelinecpu/singlecyclecpu.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Project/pipelinecpu/singlecyclecpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilinx/Project/pipelinecpu/singlecyclecpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/I_mem.coe
add_files D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/D_mem.coe
add_files D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/D_my_mem2.coe
add_files D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/I_my_mem2.coe
read_verilog -library xil_defaultlib {
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/IO/Counter_3_IO.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/ctrl_encode_def.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/EXT.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/IO/Enter.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/MIO_BUS.V
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/Multi_8CH32.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/NPC.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/PC.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/PLCPU.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/RF.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/SPIO.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/SSeg7.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/alu.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/IO/clk_div.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/myCPU/ctrl.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/dm_ctrl.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/pipe/forwarding.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/pipe/hazard_detection.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/pipe/mux.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/pipe/status_register.v
  D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/top.v
}
read_ip -quiet D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_ip -quiet D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/SSeg7.edf
read_edif D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/Multi_8CH32.edf
read_edif D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/MIO_BUS.edf
read_edif D:/Xilinx/Project/pipelinecpu/singlecyclecpu.srcs/sources_1/new/edf_file/SPIO.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx/Project/pipelinecpu/icf.xdc
set_property used_in_implementation false [get_files D:/Xilinx/Project/pipelinecpu/icf.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
